name: CreeperHeal2-Wyzebb
main: net.pdevita.creeperheal2.CreeperHeal2
version: 2.2.0-WYZEBB
api-version: 1.13
authors: ["pmdevita", "Wyzebb"]
softdepend:
  - Movecraft
  - Factions
  - Towny

commands:
  creeperheal:
    description: CreeperHeal2 commands
    usage: /creeperheal <command>
    alias: ch